# Nornir Hosts File 
---

R53: 
  hostname: 192.168.100.121
  port: 33333
  platform: cisco_ios_telnet
  username: cisco 
  password: cisco
  groups: 
    - Routers
    - Juan

SW32: 
  hostname: 192.168.100.121
  port: 33332
  platform: cisco_ios_telnet
  username: cisco
  password: cisco
  groups: 
    - Switches
    - Juan

ARISTA: 
  hostname: 192.168.100.121
  port: 33335
  platform: arista_eos_telnet
  username: Arista 
  password: arista
  groups: 
    - Switches
    - Santiago
  connection_options:
    napalm:
      extras:
        optional_args:
          transport: "telnet"

Sandbox_Cisco_XE: 
  hostname: devnetsandboxiosxe.cisco.com
  port: 22
  platform: ios
  username: admin
  password: C1sco12345
  groups: 
    - Switches
    - Juan

Sandbox_Cisco_XR: 
  hostname: sandbox-iosxr-1.cisco.com
  port: 22
  platform: ios
  username: admin
  password: C1sco12345
  groups: 
    - Switches
    - Juan
