---
- name: "Recopilar informaci贸n de IOS XE"
  hosts: iosxe
  gather_facts: no
  connection: ansible.netcommon.network_cli
  tasks:
    - name: "Mostrar versi贸n de IOS"
      cisco.ios.ios_command:
        commands:
          - "show version"
      register: output_version

    - name: "Mostrar configuraci贸n SNMP"
      cisco.ios.ios_command:
        commands:
          - "show run | include snmp-server"
      register: output_snmp

    - name: "Mostrar salida"
      debug:
        var: output_version.stdout_lines

    - name: "Mostrar configuraci贸n SNMP"
      debug:
        var: output_snmp.stdout_lines
